### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by punytomatoes** [hk21702/YA-GCal-Notion-Sync-Script#54]
Error: {"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.properties.Date.date.end should be a valid ISO 8601 date string, `null`, or `undefined`, instead was `\"5/20/2023\"`."}

I keep getting the above error and cannot figure it out.

**Comment by hk21702** [comment]
Apologies for not responding to this earlier. Double check that you're on the latest version of the script. There was a similar issue before but it should have been resolved already #43 (end of 2022). If you are certain that you're on the latest version of the script but it still happens, let me know what the date of the version you are using is (Date of the last commit on the top right corner in GitHub). Also, let me know your time zone. It might be a weird thing that happens because of your time zone or something.

**Comment by punytomatoes** [comment]
Apologies for missing this as well, it was an outdated version. Thanks
