### ISSUE TITLE
Error Calendar name null not found in dictionary. Aborting sync.

### ISSUE THREAD

**Issue by Inch-s** [hk21702/YA-GCal-Notion-Sync-Script#63]
*Make Sure You Are On The Latest **Main Branch** Version Before Reporting A Bug!!!*

**Include the following information: **
- Date of latest commit for the version of main.js you are using. (Top right corner above the code itself)
- 2 weeks ago

**Describe the bug**
The code attempts to sync to my primary calendar then claims "Calendar name Calendar not found in dictionary. Aborting sync." followed by many "Calendar name null not found in dictionary. Aborting sync."

It created the calendar name as a selection but didn't apply it

**Comment by hk21702** [comment]
It sounds like you did not create the Calendar selection choice in the Notion database correctly, or you are doing something weird when selecting the calendar in your entry. 

This error happens when you are synchronizing from Notion to GCal, specifically when the script is unable to parse the calendar name from your entry at all. From my guess, you created a new entry in the Notion database, but did not assign a calendar to it for it to sync to. You MUST do this otherwise you will get this issue.

If this entry was not one you manually created and was created as a result of a sync from GCal to Notion, let me know.

**Comment by Inch-s** [comment]
oh so if im using an existing database I have to assign all the existing entries to the calendar selection?

**Comment by hk21702** [comment]
Yes. If you are using an existing database with entries that are not yet in your GCal, you need to assign the existing entries to the calendar that you want to sync that entry to. Otherwise, the script has no clue which calendar you want to sync to. Even if you only have one calendar, having the script function this way makes it so that the script effectively assumes that you are not done modifying the entry, since you have not assigned a calendar to sync to.
