### ISSUE TITLE
Repeating events

### ISSUE THREAD

**Issue by julia562** [hk21702/YA-GCal-Notion-Sync-Script#66]
*Make Sure You Are On The Latest **Main Branch** Version Before Reporting A Bug!!!*

**Include the following information: **
I tried to find this but cannot haha — just started using this yesterday.

**Describe the bug**
I moved a repeating event in GCal, and the script didn't limit the repeating events into the future like it had done on the full sync, resulting in my being rate limited in Google Scripts. I at first noticed that in the code, RELATIVE_MAX_DAY seemingly only applies when running a full sync and not for new events, though I later realized I had misread that. I'm having trouble parsing exactly where it applies in the code. 
After this, I attempted a full sync, thinking that this would resolve the problem. However, this again resulted in hitting the rate limit after reaching 2071 in my monthly repeating event.

**Screenshots**
<img width="1142" alt="Screenshot 2023-12-10 at 10 01 54 AM" src="https://github.com/hk21702/YA-GCal-Notion-Sync-Script/assets/63875362/384af852-e432-4de4-942e-3463a03fab57">

**Additional context**

**Comment by hk21702** [comment]
So changing `RELATIVE_MAX_DAY` only works for full sync because it is a parameter that can't be changed in Google's API after the first sync is generated. My understanding of how the API works is that once you set it the first time you call it, in subsequent calls using subsequent sync tokens, the API will use the max day parameter from the time you first generated that series of sync tokens.

The consequence is that whenever you want to change `RELATIVE_MAX_DAY`, you need to do a full sync for it to apply. 

Now 2071 is way past the default 5 years that `RELATIVE_MAX_DAY` is supposed to allow the API to call so behavior is really strange. The actual parameter that is passed to the API is a date, where the relative max day global variable is turned into a date based on the date of you running the script. It could be that function is broken, there being some weird behavior with repeating events, Google changing the API behavior, or me misunderstanding how that API function worked when I first implemented it. If you can, please provide me with more info.

**Action Items for you:**

1.  What is `RELATIVE_MAX_DAY` set to in the main file? It should be an integer.
2. The commit ID for the main file that you are using. That or the date of the commit that you are using. It should be in the top right corner of the page with the code. The commit is a sting of letters and numbers, something like [08f9caa](https://github.com/hk21702/YA-GCal-Notion-Sync-Script/commit/08f9caa1a32f4bd245a990ff7c30e5255f18435f)

**Comment by StroescuDiana** [comment]
@hk21702 I have the same issue and I posted a bug report too. The relative max day for me it's set to 1825
<img width="405" alt="Screenshot 2024-05-28 at 19 57 48" src="https://github.com/hk21702/YA-GCal-Notion-Sync-Script/assets/129664856/0056aed8-46ff-4d77-b0ac-ac0bfd95f51f">
